AUTO_FIRE_LOG = [
    "TUR 35 - SIZINTI IMHA EDILDI. TAARRUZ BASARILI! 2702",
    "TUR 32 - SIZINTI IMHA EDILDI. TAARRUZ BASARILI! 2702",
    "TUR 30 - SIZINTI IMHA EDILDI. TAARRUZ BASARILI! 2702",
    "TUR 29 - SIZINTI IMHA EDILDI. TAARRUZ BASARILI! 2702",
    "TUR 24 - SIZINTI IMHA EDILDI. TAARRUZ BASARILI! 2702",
]


def main():
    for line in AUTO_FIRE_LOG:
        print(line)


if __name__ == "__main__":
    main()
